### ISSUE TITLE
Docker image for jetty 10

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#11]
<a href="https://github.com/chergey"><img src="https://avatars3.githubusercontent.com/u/6424720?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chergey](https://github.com/chergey)**
_Monday Jul 29, 2019 at 17:58 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/109_

----

Hi,
Are there plans to dockerize jetty 10 ?  I tried to replace JETTY_TGZ_URL url in https://github.com/appropriate/docker-jetty/blob/master/9.4-jre11/Dockerfile for jetty 10 but image creation fails with error: 

> *+* gpg --batch --verify jetty.tar.gz.asc jetty.tar.gz
gpg: Signature made Thu 11 Jul 2019 12:21:30 PM UTC using DSA key ID B4372146
gpg: Can't check signature: No public key

**Comment by joakime** [comment]
<a href="https://github.com/joakime"><img src="https://avatars1.githubusercontent.com/u/191721?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joakime](https://github.com/joakime)**
_Monday Jul 29, 2019 at 18:38 GMT_

----

Where did you get the image of jetty.tar.gz and jetty.tar.gz.asc?

That key isn't recognized by the the list of keys at
https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/KEYS.txt

**Comment by joakime** [comment]
<a href="https://github.com/chergey"><img src="https://avatars3.githubusercontent.com/u/6424720?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chergey](https://github.com/chergey)**
_Monday Jul 29, 2019 at 19:28 GMT_

----

From [here](https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-home/10.0.0-alpha0/jetty-home-10.0.0-alpha0.tar.gz). Why is it not recognized ? It this version being developed by other people ?

**Comment by gregw** [comment]
We should do jetty-11 at the same time

**Comment by lachlan-roberts** [comment]
@chergey Versions for Jetty-10 beta and Jetty-11 alpha (Jakarta EE) have been added to the supported image tags.
