### ISSUE TITLE
Is it possible to have eclipse-temurin:8-jre-focal variant?

### ISSUE THREAD

**Issue by tahir-uniscon** [eclipse/jetty.docker#110]
I need a Jetty docker image based on Eclipse Temurin JRE8. 
I see a Eclipse Temurin JDK8 is currently supported but not JRE8. 

I have tried to build the eclipse-temurin:8-jre-focal variant locally and it seems to work fine. 

Is it possible to add it to default set of supported variants?
I am willing to create a pull request if needed

**Comment by joakime** [comment]
Jetty 9.x are the only releases to support Java 8.

Jetty 9.x is now at End of Community Support.

See: https://github.com/eclipse/jetty.project/issues/7958

Jetty 10.x+ have a minimum Java 11 requirement.
Jetty 12.x+ has a minimum Java 17 requirement.

**Comment by tahir-uniscon** [comment]
@joakime Thanks for your reply
I just noticed that openjdk/9.4/jre8-slim is not available in this project's master branch. 
Does that mean that this is also not being maintained anymore?

**Comment by joakime** [comment]
`openjdk` is not a valid/supported docker image anymore (at the docker side)

See:

* https://github.com/docker-library/official-images/pull/12851
* https://github.com/eclipse/jetty.docker/issues/106

**Comment by tahir-uniscon** [comment]
Got it. 
But if I understand correctly, eclipse temurin is still supporting/maintaining both JDK8 and JRE8 docker base images.
Do you think jetty.docker can add support for JRE8 through [eclipse-temurin:8-jre-*](https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=8-jre)? 
In production environments it makes sense to use JRE based Jetty instead of JDK

**Comment by tahir-uniscon** [comment]
Right. Using JRE based image in production is preferable for same reason that it has smaller foot print and less chance of vulnerabilities due to lower number of executables. JSP is optional dependency and many Java web apps don't use JSP (especially true for API based backends)

**Comment by tahir-uniscon** [comment]
Also jetty.docker still has JRE8 and JRE11 base variants

**Comment by joakime** [comment]
> Also jetty.docker still has JRE8 and JRE11 base variants

Only Jetty 9 (which is at End of Community Support) has Java 8 variants.

Those on Jetty 10+, using Java 11+, have other options than a JRE release.
Those that care about reduced footprint use jlink to build custom Java releases for their exact limited usecase. (a result that is far smaller in size than even a JRE).

**Comment by tahir-uniscon** [comment]
Thanks for creating the PR. 
Is there any ETA for the PR to get merged and the new variant images becoming available on docker hub?

**Comment by joakime** [comment]
@tahir-uniscon our priority atm is the jetty releases that are in progress ...

* https://github.com/eclipse/jetty.project/issues/8555
* https://github.com/eclipse/jetty.project/issues/8557

**Comment by lachlan-roberts** [comment]
The JRE variants are now available.
See full list of supported tags at https://hub.docker.com/_/jetty.
