### ISSUE TITLE
Remove `openjdk` tag references in documentation at https://hub.docker.com/_/jetty

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#111]
Noticed while looking at Issue #110.

The [references to `openjdk` based images](https://github.com/eclipse/jetty.docker/issues/106) at https://hub.docker.com/_/jetty should either be removed, or ...

labeled as "unsupported" and/or "deprecated" and moved below the supported list of tags.

**Comment by lachlan-roberts** [comment]
These will be removed once I open a PR to `docker-official-images` to update the library file for Jetty.

I just haven't done it yet because there has been no release of Jetty since the changes were made to remove our `openjdk` images.

**Comment by lachlan-roberts** [comment]
Note that this list of tags is auto-generated from https://github.com/docker-library/official-images/blob/master/library/jetty.

We just have to manually update that file on `docker-library/official-images` with the output from our script `generate-stackbrew-library.sh`.
