### ISSUE TITLE
Jetty on top of Openjdk-8 JDK version

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#13]
<a href="https://github.com/PhantomYdn"><img src="https://avatars1.githubusercontent.com/u/1199285?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [PhantomYdn](https://github.com/PhantomYdn)**
_Monday Jan 27, 2020 at 05:53 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/131_

----

Hello!
Is it possible to make an image with openjdk-8, but JDK version (not JRE - as it's right now)?
It would be much more convenient for our project. 

A little more about use case:  our application [Orienteer](https://github.com/OrienteerBAP/Orienteer) is based on [OrientDB](https://github.com/orientechnologies/orientdb) version 2 - which require Java 8. It's running on JRE, but from time to time we need to do more deeper analysis of running instance with the aid of `jcmd` and etc. But we can't do it on top of JRE version.

**Comment by joakime** [comment]
<a href="https://github.com/PhantomYdn"><img src="https://avatars1.githubusercontent.com/u/1199285?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PhantomYdn](https://github.com/PhantomYdn)**
_Monday Jan 27, 2020 at 06:38 GMT_

----

PR created #132

**Comment by lachlan-roberts** [comment]
@PhantomYdn there are tags now available for a `9.4-jdk8` and `9.4-jdk8-slim` image variants.
