### ISSUE TITLE
Add jetty 9 images based on AdoptOpenJDK

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#14]
<a href="https://github.com/rofrance"><img src="https://avatars2.githubusercontent.com/u/13526654?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rofrance](https://github.com/rofrance)**
_Monday Jan 27, 2020 at 19:50 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/133_

----

Hi,

I would like to know if it's possible to create images based on AdoptOpenJDK instead of the Oracle OpenJDK.

AOJDK Dockerfiles are available here:
https://hub.docker.com/_/adoptopenjdk?tab=description

This would make sure that our devs don't need to build their own Dockerfiles for Jetty and instead rely on the official images available in this repo.

Thanks for your consideration,
Roberto

**Comment by x80486** [comment]
`AdoptOpenJDK` Docker images are now deprecated in favor of `Eclipse Temurin`, which in turn has `Alpine` support.

**Comment by joakime** [comment]
OpenJDK and Eclipse Temurin (based on OpenJDK) both have early pre-alpha versions of alpine support.

The official support for Alpine Linux with OpenJDK (and derivatives) is part of http://openjdk.java.net/projects/portola/

Also, as I understand it, only Eclipse Temurin 17+ has Alpine support (and it's full of caveats related to their decision to rely on musl libc breaking tons of built-in jdk features, like cipher suites, and nearly all existing JNI/JNA components)

**Comment by x80486** [comment]
`Alpine` support in `Temurin` landed for `11.x`, `16.x` and `17.x`. `Alpine` uses `musl `C` library, so indeed, one would have to account for anything that wouldn't work as expected. I think that's a well-known tradeoff, not only affecting Java, but other programming languages as well.

**Comment by lachlan-roberts** [comment]
Eclipse Temurin images are now available as well as alpine variants.
see https://hub.docker.com/_/jetty
