### ISSUE TITLE
JAVA_OPTIONS not passed through to Jetty anymore

### ISSUE THREAD

**Issue by mariokorte** [eclipse/jetty.docker#141]
The latest tags uploaded last night to docker hub broke our images based upon jetty:9.4-jre11 and jetty:10-jre11 due to missing JAVA_OPTIONS in the runtime of jetty inside the container.

We could verify that using e.g. jetty:9.4.50-jre11 the jetty runtime is started with the JAVA_OPTIONS added to the java command.
Since jetty:9.4.51-jre11 those are missing. Same for the jetty:10-jre11 builds.

We use a simple dockerfile like this:

```
FROM jetty:9.4-jre11

COPY jetty_files/ /var/lib/jetty/

ENV JAVA_OPTIONS="-Dsome.property=value"
```

We started the images, connected to the terminal and ran 'ps aux' to verify the command line of the jetty runtime.

**Comment by joakime** [comment]
Note that Jetty 9.x is currently at End of Community Support.

* https://github.com/eclipse/jetty.project/issues/7958

You should be using Jetty 10 or Jetty 11 or Jetty 12 at this point in time, or have a support contract for your old (now unsupported) version of Jetty.  
See announcement link for details.

**Comment by mariokorte** [comment]
This might be true, but as I stated: we have the same problem with the latest release tag of jetty:10-jre11

**Comment by lachlan-roberts** [comment]
@mariokorte I have updated the jetty docker images with a fix, can you please try again and report back whether it worked for you
