### ISSUE TITLE
Move official docker-jetty project to the jetty project 

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#16]
<a href="https://github.com/gregw"><img src="https://avatars2.githubusercontent.com/u/70829?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gregw](https://github.com/gregw)**
_Monday Mar 09, 2020 at 08:43 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/136_

----

It has been fantastic that jetty-docker was created and maintained by appropriate, but I think it now is falling a little into the cracks between appropriate, eclipse and webtide.
It would probably be better maintained and more responsive if moved either to the jetty project itself or to webtide (the primary maintainer of jetty).

**Comment by lachlan-roberts** [comment]
This has been completed and [appropriate/docker-jetty](https://github.com/appropriate/docker-jetty) has been archived.
