### ISSUE TITLE
jetty 9.4.29 released

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#17]
<a href="https://github.com/acutus"><img src="https://avatars3.githubusercontent.com/u/2551825?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [acutus](https://github.com/acutus)**
_Wednesday Jun 03, 2020 at 07:40 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/137_

----

Hi,

Newer versions of jetty 9.4 (jetty-9.4.28.v20200408 and jetty-9.4.29.v20200521) have been released. I was wondering if we could get tags for those (or just .29) in the official images?

**Comment by lachlan-roberts** [comment]
@acutus there are now image tags for Jetty version `9.4.30.v20200611`.

**Comment by acutus** [comment]
Great, thank you @lachlan-roberts !
