### ISSUE TITLE
Update docker images for Jetty 9.4.34.v20201102

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#32]
As pointed out in https://github.com/eclipse/jetty.project/issues/5649#issuecomment-726737189

The 9.4.34 releases is not present on Docker Hub.

**Comment by lachlan-roberts** [comment]
Opened https://github.com/docker-library/official-images/pull/9084

**Comment by joakime** [comment]
Looks like we need a new docker-library PR, as JDK-14 was dropped from the supported list.

**Comment by lachlan-roberts** [comment]
I was waiting for the jenkins build to pass which took a while as it was put in a long queue.
I have now opened https://github.com/docker-library/official-images/pull/9105, to update to JDK15 and use 9.4.34.

**Comment by lachlan-roberts** [comment]
The docker-library/official-images#9105 PR has been merged.
