### ISSUE TITLE
Build failures on Travis CI "image does not exist!"

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.docker#33]
The build has been recently failing on travis CI but still passing on jenkins. The issue seems to be related to this error message 

> 11-jre: Pulling from library/openjdk
age configuration: unknown blob

I can pull the image locally and it works so not sure why it is not working here.

Full test output https://travis-ci.com/github/eclipse/jetty.docker/jobs/441131573:
```
Setting environment variables from .travis.yml
$ export VERSION=9.4-jre11
$ bash -c 'echo $BASH_VERSION'
4.3.11(1)-release
install
1.89s$ git clone https://github.com/docker-library/official-images.git ~/official-images
before_script.1
0.01s$ env | sort
before_script.2
9.39s$ wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
before_script.3
0.00s$ cd "${VERSION}"
before_script.4
0.00s$ image="jetty:${VERSION}"
0.59s$ docker build --pull -t "$image" .
Sending build context to Docker daemon  10.75kB
Step 1/15 : FROM openjdk:11-jre
11-jre: Pulling from library/openjdk
age configuration: unknown blob
The command "docker build --pull -t "$image" ." exited with 1.
0.04s$ ~/official-images/test/run.sh "$image"
testing jetty:9.4-jre11
	image does not exist!
The command "~/official-images/test/run.sh "$image"" exited with 1.
Done. Your build exited with 1.
```

**Comment by joakime** [comment]
Could this be some of the recent docker hub limitations?

**Comment by lachlan-roberts** [comment]
@joakime I'm not sure, you'd think there would be a better error message for that.

I'm thinking it might be best to remove the Travis CI builds and just rely on our Jenkins one which we have more control over. Looks like the builds on Travis are available to everyone in eclipse so probably better to use our Jenkins if we are putting private credentials to docker hub in there.

**Comment by joakime** [comment]
We could switch to the github CI as well, I think that they have a sane docker infrastructure too.

**Comment by olamy** [comment]
get rid of Travis and use github actions see pr https://github.com/eclipse/jetty.docker/pull/31
