### ISSUE TITLE
Provide Jetty images based on openjdk:11-jre-slim

### ISSUE THREAD

**Issue by joakime** [eclipse/jetty.docker#6]
<a href="https://github.com/wenslayer"><img src="https://avatars2.githubusercontent.com/u/479376?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wenslayer](https://github.com/wenslayer)**
_Friday Feb 15, 2019 at 22:39 GMT_
_Originally opened as https://github.com/appropriate/docker-jetty/issues/103_

----

I see the current [jre-11 based Jetty image](https://github.com/appropriate/docker-jetty/blob/1ee7404fbd6c692000ab6fbeb1621ad6280d69ed/9.4-jre11/Dockerfile) is based off [openjdk:11-jre](https://github.com/docker-library/openjdk/blob/df4cff5b79d52fa311d6dff4c874f191996b583c/11/jre/Dockerfile).

To reduce image size, it would be valuable if Jetty images existed that were based off the [openjdk:11-jre-slim](https://github.com/docker-library/openjdk/blob/df4cff5b79d52fa311d6dff4c874f191996b583c/11/jre/slim/Dockerfile) image.

Thank you for your consideration.

**Comment by joakime** [comment]
<a href="https://github.com/gregw"><img src="https://avatars2.githubusercontent.com/u/70829?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gregw](https://github.com/gregw)**
_Sunday Feb 17, 2019 at 09:22 GMT_

----

@md5 I'm guessing we should just make another variant rather than make everybody use slim?
@wenslayer I'm currently on vacation, so wont get around to this for a few weeks.... but if you wanted to prepare a PR, then I can review and merge if it checks out.

**Comment by joakime** [comment]
<a href="https://github.com/md5"><img src="https://avatars0.githubusercontent.com/u/76367?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [md5](https://github.com/md5)**
_Wednesday Feb 20, 2019 at 07:23 GMT_

----

> @md5 I'm guessing we should just make another variant rather than make everybody use slim?

Yeah, I think this would be another variant. It makes sense to me, given the lack of a JDK 11 for Alpine for the time being.

**Comment by joakime** [comment]
<a href="https://github.com/gregw"><img src="https://avatars2.githubusercontent.com/u/70829?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gregw](https://github.com/gregw)**
_Thursday Oct 24, 2019 at 06:29 GMT_

----

@tianon can you comment a bit more on the implications of docker-library/openjdk#322 ?

Also, I think it is time to look at jkd13... there are currently slim and buster varieties of that.

**Comment by joakime** [comment]
<a href="https://github.com/gregw"><img src="https://avatars2.githubusercontent.com/u/70829?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gregw](https://github.com/gregw)**
_Monday Dec 16, 2019 at 06:46 GMT_

----

The merge of #121 created the slim images, but has broken the architecture rules.

**Comment by joakime** [comment]
<a href="https://github.com/gregw"><img src="https://avatars2.githubusercontent.com/u/70829?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gregw](https://github.com/gregw)**
_Thursday Dec 19, 2019 at 21:20 GMT_

----

https://github.com/docker-library/official-images/pull/7134

**Comment by lachlan-roberts** [comment]
@wenslayer there are now jetty images available based off `openjdk:11-jre-slim`.
