### ISSUE TITLE
Simplify continuous integration.

### ISSUE THREAD

**Issue by lachlan-roberts** [eclipse/jetty.docker#61]
We currently have the webtide jenkins build, travis CI and github CI.

The only reliable one seems to be the jenkins build. So maybe we should simply our CI by removing the travis and github CI builds.

**Comment by lachlan-roberts** [comment]
@olamy what do you think?

**Comment by olamy** [comment]
@lachlan-roberts definitely agree with that! not sure how long travis will be free and github actions looks to have some network issue with keys server.
Let's use only Jenkins ;)
