### ISSUE TITLE
Jetty image based on Amazon Corretto

### ISSUE THREAD

**Issue by matsaune** [eclipse/jetty.docker#63]
Would it be possible to provide jetty images based an Amazon Corretto (https://hub.docker.com/_/amazoncorretto) in addition to openJDK? Or has this already been considered and decided as a no go?

**Comment by lachlan-roberts** [comment]
The problem is that if we add images based on Amazon Corretto we will need to add and maintain possibly another 24 images for every Jetty/JDK combination. And then there has also been requests for other base images such as AdoptOpenJDK and Alpine. So the amount of images we are providing and maintaining would dramatically increase if we supported all of these.

@gregw what do you think we should do?

**Comment by gregw** [comment]
I think it's fairly simple to support, even if numbers multiply.  A supported jdk in AWS is a good target audience for jetty users that are interested in supported software... So potentially good business too

**Comment by joakime** [comment]
What about adoptium?

**Comment by sbordet** [comment]
@gregw the problem with Corretto and other OpenJDK vendors is that they add their own patches, so you're not really running the official OpenJDK tag, but some code with some backport from future OpenJDK versions.

For example, Corretto 8 comes with patches from OpenJDK 9, 10, 11, 12, etc.: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/patches.html

We don't test Jetty with these vendor-specific OpenJDK versions, so we don't even know if Jetty works on these OpenJDK vendors.

My take is that we should provide default images based on official OpenJDK builds based on official source tags with no vendor patches, and possibly provide a script such as:

```
$ buildJettyImage.sh <openjdk-vendor-label> <jetty-version>
```

and then people can build their own image using the OpenJDK vendor they want with the Jetty version they want.

**Comment by gregw** [comment]
@sbordet but we essentially already have that script in the docker build system. Simple to add a JVM to the enumeration and then image gets built automatically.

Why would we provide a script and then not run it to produce an image?

**Comment by sbordet** [comment]
> Why would we provide a script and then not run it to produce an image?

Because who knows if it works on JDKs that we don't test?

**Comment by gregw** [comment]
That's a circular argument. If you don't build an image then it can't be tested so therefore you shouldn't build the image???

We should be doing at least minimal tests on all images generated so again this can be easily automated if it's not already.

Ultimately this is just removing a hurdle for entry

**Comment by YTN01** [comment]
Any decision on this? My team is also considering running Jetty on Azul Zulu JDK.

**Comment by lachlan-roberts** [comment]
@YTN01 I am preparing a PR to restructure the project to allow us to more easily add support for new base images.
If this is approved it will be easy to add support for any additional base images.

**Comment by YTN01** [comment]
@lachlan-roberts wonderful. Thanks for the update.

**Comment by opengeekv2** [comment]
Adoptium is the cleanest build of all and continues the work of adoptopenjdk. The main problem of relying in openjdk docker images is that they pull the binaries from jdk.oracle.com. Although v17 is an LTS the binaries in jdk.oracle.com won't be updated the whole LTS lifetime but just 6 months as mentioned in this issue (https://github.com/docker-library/openjdk/issues/485#issuecomment-1013364661)

Adoptium binaries will be mantained for all the LTS lifespan. Adoptium binaries are a build from OpenJDK sources. Other official docker images like gradle have already migrated to the eclipse-adoptium image as a base.

**Comment by lachlan-roberts** [comment]
Images are now available based on `eclipse-temurin` and `amazoncorretto`. 
See list of supported tags here : https://hub.docker.com/_/jetty

Azul Zulu images are also available but you will need to build them yourself. The `azul/zulu-openjdk` images are not part of the docker official images program so we cannot publish official Jetty images based on it. You can download this project and run `make` and it will build all images including the `azul/zulu-openjdk` ones.

**Comment by nagarpankaj** [comment]
@lachlan-roberts Can you please explain about **make** command that you talked about.

**Comment by lachlan-roberts** [comment]
@nagarpankaj you don't need to use make.

From the project root you can run `make` to build all images, `make amazoncorretto/10.0/jdk17` to build only that image.

Or you could just specify the docker build command manually and do something like
```
docker build -t jetty:10.0-jdk17-amazoncorretto amazoncorretto/10.0/jdk17
```
