### ISSUE TITLE
Need linux/arm64 arch for jetty-9.4 with jre8

### ISSUE THREAD

**Issue by PhantomYdn** [eclipse/jetty.docker#64]
Hello,

Jetty seems to be very attractive to be used on raspberry Pi and etc., but unfortunately there is no support of linux/arm64 for jre8. Could you please add?

**Comment by joakime** [comment]
Last time I looked, Docker wasn't available on Raspberry Pi.
Has that changed?

**Comment by PhantomYdn** [comment]
@joakime ,
Yep - has changed:) It's not fully straightforward, but possible.
https://www.raspberrypi.org/blog/docker-comes-to-raspberry-pi/
https://italypaleale.medium.com/yes-you-can-run-docker-on-raspbian-50722bf106dc
