### ISSUE TITLE
docker entry point doesn't pass command line arguments to jetty anymore.

### ISSUE THREAD

**Issue by nikel123** [eclipse/jetty.docker#74]
The commit 6b18aef0b55c4ecbc6106bae4a6267702c2e0490 "Update docker-entrypoint and generate-jetty.start with update script" breaks passing arguments to jetty. We are heavely relying on it to pass our application parameters. The culprit is "/generate-jetty-start.sh", which is not passed any "$@" arguments anymore.

**Comment by joakime** [comment]
PR #75 opened

**Comment by joakime** [comment]
You can always add a start ini with the line `jetty.httpConfig.uriCompliance=RFC3986` now.

Be it `${jetty.base}/start.ini` or something new in `${jetty.base}/start.d/xwiki.ini`

**Comment by vmassol** [comment]
> You can always add a start ini with the line jetty.httpConfig.uriCompliance=RFC3986 now.

You mean by using `docker cp` to copy such a file inside the container? I don't see how to do what you suggest using volume mapping since that'd mean mapping the whole jetty base directory and I don't want to have to provide that from my host. Now with `docker cp` the problem is that jetty will already be started when the copy happens...

Any idea how to perform your idea using the docker image and without a custom image?

Thanks a lot for your idea and help, much appreciated! :)

**Comment by vmassol** [comment]
> I don't see how to do what you suggest using volume mapping since that'd mean mapping the whole jetty base directory and I don't want to have to provide that from my host.

ah, maybe mapping `${jetty.base}/start.d` would work better if there's no other files in there by default. Would need to check it.

**Comment by vmassol** [comment]
> Would need to check it.

hmm bad luck:

```
vmassol ~/dev/xwiki/versions $ docker exec -it 190 bash -l
ls jetty@1901a7e76925:~$ ls -l
total 20
-rw-r--r-- 1 jetty jetty 3057 Nov 23 14:41 jetty.start
drwxr-xr-x 3 jetty jetty 4096 Nov 18 13:42 lib
drwxr-xr-x 2 jetty jetty 4096 Nov 18 13:42 resources
drwxr-xr-x 2 jetty jetty 4096 Nov 18 13:42 start.d
drwxr-xr-x 1 jetty jetty 4096 Nov 23 14:41 webapps
jetty@1901a7e76925:~$ cd start.d
jetty@1901a7e76925:~/start.d$ ls -l
total 32
-rw-r--r-- 1 jetty jetty  648 Nov 18 13:42 deploy.ini
-rw-r--r-- 1 jetty jetty  209 Nov 18 13:42 ext.ini
-rw-r--r-- 1 jetty jetty 1552 Nov 18 13:42 http.ini
-rw-r--r-- 1 jetty jetty  178 Nov 18 13:42 jsp.ini
-rw-r--r-- 1 jetty jetty  181 Nov 18 13:42 jstl.ini
-rw-r--r-- 1 jetty jetty  267 Nov 18 13:42 resources.ini
-rw-r--r-- 1 jetty jetty 2876 Nov 18 13:42 server.ini
-rw-r--r-- 1 jetty jetty  216 Nov 18 13:42 websocket.ini
jetty@1901a7e76925:~/start.d$ 
```

**Comment by vmassol** [comment]
Cool, I got to work with TestContainers with:

```
        MountableFile serverIniFile = MountableFile.forClasspathResource("/server.ini");
        this.servletContainer.withCopyFileToContainer(serverIniFile, "/var/lib/jetty/start.d/server.ini");
```

Thanks

**Comment by lachlan-roberts** [comment]
I think PR #75 is good to go. I will merge that and start the release now instead of waiting for next version of Jetty.

**Comment by lachlan-roberts** [comment]
@vmassol @nikel123 the updated images should now be available.

**Comment by vmassol** [comment]
@lachlan-roberts Thanks a lot. Just tested and it worked :)
